services:
  mkdocs:
    image: squidfunk/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - ./blog:/docs/blog
      - ./mkdocs.yml:/docs/mkdocs.yml
    # stdin_open: true
    # tty: true